version: '3.4'
services:

  database:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=gonso
    volumes:
      - database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    restart: unless-stopped
    build:
      context: api
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres

  frontend:
    restart: unless-stopped
    build:
      context: .

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
        - '81:81'
        - '443:443'
        - '80:80'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    environment:
      - PERIOD=5m
      - CONFIG={"settings":[{"provider":"namecheap","domain":"lopezcastilla.net","host":"buildercheck","password":"${DDNS_PWD}"}]}

volumes:
  database: { }
  pgadmin-data:
  data: { }
  letsencrypt: { }