name: Build API

on:
  push:
    branches:
      - main
      - master

jobs:
  build_api:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          context: "{{defaultContext}}:api"
          tags: simplecloudquestions/example_docker:latest

  build_web_frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: simplecloudquestions/example_docker:latest

  android-release-build:
    name: android-release-build
    runs-on: ubuntu-latest
    container: ghcr.io/niklaslehnfeld/flutter-essentials-docker:master
    steps:
      - uses: actions/checkout@v2
      - uses: NiklasLehnfeld/flutter-android-build-action@v1
        id: android-build
        with:
          release: true
          keystore: ${{ secrets.KEYSTORE }}
          keystore-pwd: "${{ secrets.KEYSTORE_PASSWORD }}"
          key-pwd: "${{ secrets.KEY_PASSWORD }}"
      - name: Archive AP